In [1]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv('datos_consolidados.csv', header = None)

In [16]:
data

,0,1,2,3,4,5
0,2.10,3.55,3.60,Atletico Bucaramanga,Alianza Petrolera,2023-04-25
1,2.15,3.25,3.80,Deportivo Pasto,La Equidad Seguros,2023-04-25
2,3.25,3.00,2.55,Atletico Huila,Independiente Medellin,2023-04-25
3,2.10,3.20,4.05,Once Caldas Manizales,Boyaca Chico,2023-04-26
4,1.70,3.70,5.65,Deportes Tolima,Jaguares de Cordoba,2023-04-26
...,...,...,...,...,...,...
115,1.46,4.30,8.40,Deportivo Cali,Jaguares de Cordoba,2023-10-24
116,2.63,3.05,3.00,Atletico Bucaramanga,La Equidad Seguros,2023-10-24
117,3.26,3.15,2.40,Deportivo Pereira,Junior Barranquilla,2023-10-24
118,1.55,4.05,6.75,Millonarios FC,Boyaca Chico,2023-10-24
119,1.77,3.70,5.00,America de Cali,Millonarios FC,30 de octubre